name: Pre-Commit

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Specify your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pre-commit vale mypy pylint

    - name: Copy the pre-commit config file
      run: cp .pre-commit-config.yaml ./.git/hooks/pre-commit

    - name: Install mypy types
      run: mypy --install-types --non-interactive

    - name: Run pre-commit hooks
      run: pre-commit run --all-files

    - name: Run tests
      run: |-
        pip install pytest
        pytest tests/
